INFO 2025-08-17 18:11:09,331 [logs.py (__call__)] USER 2054556183 ROUTER: user_slash_command_router  CALLBACK: start
INFO 2025-08-17 18:11:12,665 [logs.py (__call__)] USER 2054556183 ROUTER: user_slash_command_router  CALLBACK: start
INFO 2025-08-17 18:11:13,669 [logs.py (__call__)] USER 2054556183 ROUTER: user_slash_command_router  CALLBACK: start
INFO 2025-08-17 18:12:39,300 [logs.py (__call__)] USER 2054556183 ROUTER: user_slash_command_router  CALLBACK: start
ERROR 2025-08-17 18:12:39,300 [logs.py (__call__)] division by zero
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\������� ����\aiogram_bot_template\bot\middleware\logs.py", line 30, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\������� ����\aiogram_bot_template\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\������� ����\aiogram_bot_template\bot\handlers\slash_command\user\router.py", line 12, in start
    5/0
ZeroDivisionError: division by zero